import Link from 'next/link';
import { ArrowUpRight, Download, Code2 } from 'lucide-react';
import { REPO_URL } from '@/lib/historical';

export const metadata = { title: 'Review & reproduce GERT', description: 'A ten-minute review of historical ERCOT load, explicit capacity assumptions, and reproducible calculations.' };

export default function ReviewPage() {
  return <div className="max-w-5xl space-y-8 pb-14">
    <header className="border-b border-black/20 pb-8"><span className="technical-label text-[#b73700]">Open review / Energy · Mathematics · Education</span><h1 className="display-serif mt-4 text-[clamp(3rem,7vw,6rem)] leading-[0.95] tracking-[-0.05em]">Try it.<br />Check it. Challenge it.</h1><p className="mt-6 max-w-2xl text-sm leading-6 text-[#4f4e4a]">GERT invites independent review of its historical load analysis. The most useful contribution is a reproduced result, a mistaken assumption you identify, or a concrete improvement to the way evidence is explained.</p></header>
    <section className="border border-[#175a73] bg-[#dfe8ea] p-6"><h2 className="display-serif text-3xl">Start with a five-minute counterexample.</h2><p className="mt-3 text-sm leading-6">Not ready for a full technical review? Make two invented worlds produce identical meter readings and inspect why their unserved energy differs. Includes a short facilitator guide; no account or installation needed.</p><Link href="/briefs/same-meter" className="mt-4 inline-block text-sm font-semibold underline">Open Same meter, two worlds →</Link><p className="mt-3 text-xs leading-5">An introductory teaching activity, not a completed review of the historical dataset.</p></section>
    <section className="border border-[#141414] bg-[#f3c64d] p-6 sm:p-8"><h2 className="display-serif text-3xl">One complete review, about 10 minutes.</h2><ol className="mt-5 list-decimal space-y-4 pl-5 text-sm leading-6">
      <li><Link href="/history?case=summer-2023&capacity=80000&reduction=0" className="font-semibold underline">Open the summer case at 80,000 MW and 0% reduction.</Link> Note the hours above assumed capacity and the gap energy.</li>
      <li>Switch to 5% reduction. Explain why the hours and energy change. Can you distinguish the actual observations from the two assumptions?</li>
      <li>Download the JSON report and hourly CSV. Recompute one row as max(0, adjusted load − capacity). Sum the hourly gaps to check the total in MWh.</li>
      <li>Inspect the winter case. Why would measured load during outages be insufficient to reconstruct unmet demand?</li>
      <li>Share one result you checked and one change you would make. A negative finding is useful.</li>
    </ol><Link href="/history?case=summer-2023&capacity=80000&reduction=0" className="mt-6 inline-flex items-center gap-2 bg-[#141414] px-5 py-3 text-sm text-white">Start the review <ArrowUpRight size={16} /></Link></section>
    <section className="grid gap-6 md:grid-cols-2"><div className="border border-black/20 bg-[#f7f6f2] p-6"><Code2 size={24} /><h2 className="display-serif mt-4 text-3xl">Reproduce without the website</h2><p className="mt-4 text-sm leading-6">The archive extractor and independent report checker use Python's standard library. The source files, data version, checksums, formulas and limits are documented in the repository.</p><a href={`${REPO_URL}/blob/main/docs/HISTORICAL_LAB.md`} className="mt-5 inline-block text-sm font-semibold underline">Reproduction instructions</a></div>
      <div className="border border-black/20 bg-[#f7f6f2] p-6"><Download size={24} /><h2 className="display-serif mt-4 text-3xl">Use it in a small workshop</h2><p className="mt-4 text-sm leading-6">A ready-to-use 20-minute exercise covers load, power versus energy, counterfactual assumptions, and the difference between arithmetic and a reliable operational decision.</p><a href={`${REPO_URL}/blob/main/docs/WORKSHOP.md`} className="mt-5 inline-block text-sm font-semibold underline">Open the facilitator guide</a></div></section>
    <section className="border-t border-black/20 pt-8"><h2 className="display-serif text-4xl">Leave an inspectable review.</h2><p className="mt-4 max-w-3xl text-sm leading-6">Use the structured GitHub form for a reproducible review, or add one concise field note to the public discussion. You choose whether to submit. GitHub posts are public: do not include personal contact information, private datasets, credentials, or another person&apos;s words without permission.</p><div className="mt-5 flex flex-wrap gap-3"><a href={`${REPO_URL}/issues/new?template=historical_review.yml`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-[#141414] px-5 py-3 text-sm font-semibold">Write a structured review <ArrowUpRight size={16} /></a><a href={`${REPO_URL}/discussions/3`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 bg-[#141414] px-5 py-3 text-sm font-semibold text-white">Add one public field note <ArrowUpRight size={16} /></a></div><Link href="/community" className="mt-5 inline-block text-sm font-semibold underline">See the community evidence ledger →</Link><p className="mt-4 text-xs leading-5 text-[#6d6b66]">A review records what you actually completed. Feedback is not automatically an endorsement; hosting a session, contributing a critique, and adopting software are different outcomes.</p></section>
    <section className="border-t border-black/20 pt-6 text-sm leading-6"><h2 className="font-semibold">What this release establishes</h2><p className="mt-2">Three public-data cases, reproducible deterministic calculations, downloadable reports, and an open review process. User-defined capacity is not historical capacity; counterfactual gap energy is not expected unserved energy. The probabilistic research candidate remains gated until its validation requirements pass.</p></section>
  </div>;
}
