import matplotlib
matplotlib.use('Agg') # Non-interactive backend for server
import matplotlib.pyplot as plt
import io
import base64
import random
import math
from datetime import datetime, timedelta
from typing import Dict, List, Tuple

# ==========================================
# 1. Templates & Copywriting (Bilingual)
# ==========================================

TEMPLATES = {
    "title": {
        "en": "GERT Extreme Risk Bulletin",
        "cn": "GERT 极端风险通报"
    },
    "headers": {
        "summary": {"en": "Executive Summary", "cn": "执行摘要"},
        "analysis": {"en": "Load & Risk Analysis (Next 24h)", "cn": "负载与风险分析 (未来24小时)"},
        "advice_public": {"en": "Action Plan: Public", "cn": "行动建议：公众"},
        "advice_grid": {"en": "Action Plan: Grid Operators", "cn": "行动建议：电网运营机构"},
        "footer": {"en": "Generated by GERT AI Engine. Not for official regulatory use.", "cn": "由 GERT AI 引擎生成。仅供参考，非官方监管文件。"}
    },
    "risk_descriptions": {
        "LOW": {
            "en": "Grid conditions are stable. Standard operations.",
            "cn": "电网运行平稳。维持标准作业程序。"
        },
        "MODERATE": {
            "en": "Elevated load expected. Monitor reserves closely.",
            "cn": "预计负载升高。需密切监控备用容量。"
        },
        "HIGH": {
            "en": "Reserves may fall below safety margins. Voluntary conservation requested.",
            "cn": "备用容量可能跌破安全边际。建议实行自愿节能。"
        },
        "EXTREME": {
            "en": "CRITICAL EMERGENCY. Rolling blackouts probable. Immediate load shedding required.",
            "cn": "极度紧急状态。极有可能发生轮流停电。必须立即执行负荷削减。"
        }
    },
    "advice": {
        "LOW": {
            "public": [
                {"en": "No specific action required.", "cn": "无需采取特殊行动。"},
                {"en": "Monitor local news for weather updates.", "cn": "留意当地气象新闻更新。"}
            ],
            "grid": [
                {"en": "Perform routine maintenance.", "cn": "执行例行维护。"},
                {"en": "Validate forecast models.", "cn": "校准预测模型。"}
            ]
        },
        "MODERATE": {
            "public": [
                {"en": "Shift heavy appliance use to off-peak hours.", "cn": "将大功率电器使用移至非高峰时段。"},
                {"en": "Check insulation on windows/doors.", "cn": "检查门窗隔热密封情况。"}
            ],
            "grid": [
                {"en": "Cancel scheduled maintenance outages.", "cn": "取消计划内的维护停机。"},
                {"en": "Pre-warm auxiliary boilers.", "cn": "预热辅助锅炉。"}
            ]
        },
        "HIGH": {
            "public": [
                {"en": "Set thermostat to 68°F (20°C) or lower.", "cn": "将恒温器设定在 20°C 或更低。"},
                {"en": "Avoid using washing machines/dryers.", "cn": "避免使用洗衣机/烘干机。"},
                {"en": "Charge mobile devices and battery packs.", "cn": "为移动设备和充电宝充满电。"}
            ],
            "grid": [
                {"en": "Activate Demand Response (DR) programs.", "cn": "启动需求响应 (DR) 计划。"},
                {"en": "Import max available power from neighbors.", "cn": "从邻近电网最大化进口电力。"},
                {"en": "Issue public conservation alerts.", "cn": "发布公众节能预警。"}
            ]
        },
        "EXTREME": {
            "public": [
                {"en": "Prepare emergency kit (flashlights, water, food).", "cn": "准备应急包（手电筒、水、食物）。"},
                {"en": "Unplug sensitive electronics to prevent surge damage.", "cn": "拔掉敏感电子设备以防浪涌损坏。"},
                {"en": "If power is lost, keep fridge closed.", "cn": "如果停电，请保持冰箱关闭。"},
                {"en": "DO NOT use gas stoves for heating.", "cn": "严禁使用燃气灶取暖（防止一氧化碳中毒）。"}
            ],
            "grid": [
                {"en": "INITIATE TIER 3 LOAD SHEDDING.", "cn": "启动三级负荷削减（轮流停电）。"},
                {"en": "Secure critical infrastructure (hospitals, fire stations).", "cn": "保障关键基础设施（医院、消防）供电。"},
                {"en": "Deploy black-start units for contingency.", "cn": "部署黑启动机组以防万一。"}
            ]
        }
    }
}

# ==========================================
# 2. Data Simulation
# ==========================================

def simulate_extreme_window() -> Tuple[List[int], List[float], List[float], List[float]]:
    """
    Simulates a 24-hour window of a 'Polar Vortex' event.
    Returns: hours, P50 load, P99 load, Capacity
    """
    hours = list(range(24))
    p50_series = []
    p99_series = []
    capacity_series = []
    
    # Base pattern
    for h in hours:
        # Extreme cold curve
        base_load = 45000 + 10000 * math.sin((h - 6) / 24 * 2 * math.pi)
        
        # Volatility spike in evening peak (hour 17-21)
        if 17 <= h <= 21:
            volatility = 8000
            spike = 5000
        else:
            volatility = 2000
            spike = 0
            
        p50 = base_load + spike
        p99 = p50 + (volatility * 2.33)
        
        # Capacity drops due to freezing (Simulated)
        capacity = 58000 - (h * 100) # Gradual capacity loss
        
        p50_series.append(p50)
        p99_series.append(p99)
        capacity_series.append(capacity)
        
    return hours, p50_series, p99_series, capacity_series

# ==========================================
# 3. Chart Generation
# ==========================================

def generate_chart_base64(hours, p50, p99, capacity) -> str:
    plt.figure(figsize=(10, 4), dpi=100)
    
    # Plotting
    plt.plot(hours, p99, color='#dc2626', label='P99 Extreme Load (Risk)', linewidth=2)
    plt.plot(hours, p50, color='#4f46e5', label='P50 Median Load', linewidth=2, linestyle='--')
    plt.plot(hours, capacity, color='#16a34a', label='Grid Capacity', linewidth=2, linestyle=':')
    
    # Fill risk zone
    plt.fill_between(hours, p50, p99, color='#dc2626', alpha=0.1)
    
    # Styling for "Paper" look
    plt.title("24-Hour Quantile Forecast vs. Capacity", fontsize=12, fontweight='bold')
    plt.xlabel("Hour of Day")
    plt.ylabel("Load (MW)")
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.legend(loc='upper left')
    plt.tight_layout()
    
    # Save to buffer
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)
    data = base64.b64encode(buf.read()).decode('utf-8')
    plt.close()
    
    return data

# ==========================================
# 4. HTML Generator
# ==========================================

def generate_bulletin_html():
    # 1. Get Data
    hours, p50, p99, capacity = simulate_extreme_window()
    
    # 2. Determine Risk Level (Max P99 vs Min Capacity gap)
    max_risk_score = 0
    for i in range(len(hours)):
        margin = capacity[i] - p99[i]
        if margin <= 0:
            score = 100
        else:
            score = max(0, 100 - (margin / 5000 * 100))
        if score > max_risk_score:
            max_risk_score = score
            
    if max_risk_score >= 90: risk_level = "EXTREME"
    elif max_risk_score >= 75: risk_level = "HIGH"
    elif max_risk_score >= 40: risk_level = "MODERATE"
    else: risk_level = "LOW"

    # 3. Generate Chart
    chart_b64 = generate_chart_base64(hours, p50, p99, capacity)
    
    # 4. Build HTML
    t = TEMPLATES
    date_str = datetime.now().strftime("%Y-%m-%d %H:%00")
    
    risk_color = {
        "LOW": "#10b981", "MODERATE": "#f59e0b", "HIGH": "#f97316", "EXTREME": "#ef4444"
    }[risk_level]

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>GERT Bulletin</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
            @media print {{
                body {{ -webkit-print-color-adjust: exact; }}
                .no-print {{ display: none; }}
            }}
            body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background: white; color: #1f2937; }}
        </style>
    </head>
    <body class="p-8 max-w-4xl mx-auto border-t-8" style="border-color: {risk_color}">
        
        <!-- Header -->
        <div class="flex justify-between items-start mb-8 border-b pb-4">
            <div>
                <h1 class="text-3xl font-bold text-slate-900">{t['title']['en']}</h1>
                <h2 class="text-xl text-slate-600">{t['title']['cn']}</h2>
            </div>
            <div class="text-right">
                <div class="text-sm text-slate-500">ISSUED / 发布时间</div>
                <div class="font-mono font-bold text-lg">{date_str}</div>
                <div class="mt-2 inline-block px-3 py-1 text-white font-bold rounded" style="background-color: {risk_color}">
                    LEVEL: {risk_level}
                </div>
            </div>
        </div>

        <!-- Summary -->
        <section class="mb-8 bg-slate-50 p-6 rounded-lg border-l-4" style="border-color: {risk_color}">
            <h3 class="text-sm font-bold uppercase text-slate-500 mb-2">{t['headers']['summary']['en']} / {t['headers']['summary']['cn']}</h3>
            <p class="text-lg font-medium mb-2">{t['risk_descriptions'][risk_level]['en']}</p>
            <p class="text-lg font-medium text-slate-600">{t['risk_descriptions'][risk_level]['cn']}</p>
        </section>

        <!-- Chart -->
        <section class="mb-8">
            <h3 class="text-sm font-bold uppercase text-slate-500 mb-4">{t['headers']['analysis']['en']} / {t['headers']['analysis']['cn']}</h3>
            <div class="border rounded p-2">
                <img src="data:image/png;base64,{chart_b64}" class="w-full" alt="Risk Chart">
            </div>
            <p class="text-xs text-center text-slate-400 mt-2">
                Red Line: P99 Extreme Scenario (1% Probability) | Green Line: Total Available Capacity
            </p>
        </section>

        <!-- Advice Columns -->
        <div class="grid grid-cols-2 gap-8 mb-8">
            <!-- Public -->
            <div>
                <h3 class="text-lg font-bold border-b-2 border-slate-200 pb-2 mb-4">
                    🏢 {t['headers']['advice_public']['en']}<br>
                    <span class="text-sm font-normal text-slate-500">{t['headers']['advice_public']['cn']}</span>
                </h3>
                <ul class="space-y-3">
                    {''.join([f'<li class="flex items-start"><span class="mr-2 text-blue-500">●</span><div><div class="font-medium">{item["en"]}</div><div class="text-sm text-slate-500">{item["cn"]}</div></div></li>' for item in t['advice'][risk_level]['public']])}
                </ul>
            </div>

            <!-- Grid -->
            <div>
                <h3 class="text-lg font-bold border-b-2 border-slate-200 pb-2 mb-4">
                    ⚡ {t['headers']['advice_grid']['en']}<br>
                    <span class="text-sm font-normal text-slate-500">{t['headers']['advice_grid']['cn']}</span>
                </h3>
                <ul class="space-y-3">
                    {''.join([f'<li class="flex items-start"><span class="mr-2 text-red-500">●</span><div><div class="font-medium">{item["en"]}</div><div class="text-sm text-slate-500">{item["cn"]}</div></div></li>' for item in t['advice'][risk_level]['grid']])}
                </ul>
            </div>
        </div>

        <!-- Footer -->
        <div class="text-center text-xs text-slate-400 mt-12 pt-4 border-t">
            {t['headers']['footer']['en']}<br>{t['headers']['footer']['cn']}
        </div>

        <div class="no-print mt-6 text-center">
            <button onclick="window.print()" class="bg-indigo-600 text-white px-6 py-2 rounded hover:bg-indigo-700">Print / Save as PDF</button>
        </div>
    </body>
    </html>
    """
    return html

if __name__ == "__main__":
    # Test run
    print(generate_bulletin_html()[:500])
